### ISSUE TITLE
Localize Replay Examination page

### ISSUE THREAD

**Issue by akouryy** [Equim-chan/mjai-reviewer#102]
Is it possible to localize https://mjai.ekyu.moe/report/***.html?
Probably I can help, though it may disturb you as you'd not be able to edit English texts directly in `templates/report.tera` anymore.

**Comment by Equim-chan** [comment]
I also want to do this, but I'm not able to find a suitable i18n framework.

**Comment by akouryy** [comment]
How about `fluent-templates`? It seems nice and I'm now [experimenting](https://github.com/akouryy/mjai-reviewer/commit/b8715a5e391bfaba976876ee5057587ffb039333) with it.

**Comment by akouryy** [comment]
Unfortunately I could not build Mortal, and [my branch](https://github.com/akouryy/mjai-reviewer/tree/102-localize-render) is only tested with akochan outputs. So I'd like to leave it to you @Equim-chan.

**Comment by Equim-chan** [comment]
Works for me.

**Comment by Equim-chan** [comment]
Works for me.
