### ISSUE TITLE
Augment the "Expand-difference only" function

### ISSUE THREAD

**Issue by TaikiShuttle** [Equim-chan/mjai-reviewer#104]
Currently, `Expand` function in mjai-reviewer only has three options: All, Diff only, None.
However, differences can be large or small. And users may care more about those large differences.
Is it possible to create a filter that let users to choose the scale of difference? For example, I only want to expand those differences where my move is not in top 3.
That would be really helpful!

当前，`Expand` 功能只支持 All, Diff only, None 三种展开方式。
但是考虑到difference也有大小之分，用户可能更加关心自己和Mortal出入比较大的错误，即那些特别严重的恶手。
所以如果能够让用户自己设定一个filter的值，比方说我只想看没有进入mortal前三rank的difference，亦或者我只想看我的鸡打（mortal `πτ(a∣s)×100 < 20` ）。这个功能会帮助用户更快定位到自己有疑问的地方。
感谢！

**Comment by Equim-chan** [comment]
I understand this scenario, but I prefer not to make assumptions about Mortal's output table. This is also one of the reasons why I don't endorse rating, didn't implement bad%, and only display the matching rate by default.

To quote the FAQ:
> The single-line output (starting with `Mortal:`) is the actual final decision made by the AI, while the expanded table provides additional, intermediate information that is totally optional and may be altered or even removed in a future version. [...] Furthermore, the table is just a by-product of the AI, and focusing too much on building it may hinder finding better ways to build a stronger AI.

我能理解这个场景，但我不想对 Mortal 输出的表格做假设。这也是我不推崇 rating，不做恶手率，而默认只有匹配率的原因。

引用 FAQ：
> 单行的输出（以 `Mortal:` 开头的）是 AI 实际做出的决策，而展开的表格里的是附加的中间信息。这些信息完全是可选的，并在将来的版本中可能修改甚至移除。[...] 此外，该表格只是 AI 的副产品，过度专注于构建这张表可能会妨碍实现更强的 AI。
