### ISSUE TITLE
Paipu of mahjong soul failed to download now

### ISSUE THREAD

**Issue by JustLikeTT** [Equim-chan/mjai-reviewer#105]
Paipu of mahjong soul failed to download which engine is mortal 3.1
![image](https://user-images.githubusercontent.com/22533673/233775984-d18dc528-5d2d-4feb-99b8-89633c99ba98.png)

**Comment by wandugu** [comment]
+1

**Comment by Rgyzd9870** [comment]
+1

**Comment by wlllssd** [comment]
same error

**Comment by lgqdaxia** [comment]
same

**Comment by Equim-chan** [comment]
This is out of my control. It seems to be a Mahjong Soul issue.

**Comment by Equim-chan** [comment]
Currently, there are some chances for it to work, and the odds are higher at off-peak hours.

**Comment by CatalinaCharlotte** [comment]
Are there any traffic attacks?

**Comment by Equim-chan** [comment]
Thanks to the help from 雀魂牌譜屋, this problem has been greatly mitigated now, especially for older game records.
