### ISSUE TITLE
an error occurred during the task, please check your inputs

### ISSUE THREAD

**Issue by Kei-Toba** [Equim-chan/mjai-reviewer#106]
When analyzing mahjonsoul's paifu using akochan on mjai.ekyu.moe, error sentence shown on title was output. It seems like a bug.
雀魂の牌譜をmjai.ekyu.moeで解析するとタイトルのエラー文が表示されました。これはバグでしょうか？

**Comment by Equim-chan** [comment]
You didn't provide your inputs in this issue, then how could I possibly check that?

**Comment by Kei-Toba** [comment]
I tried it again under the same conditions and no error was displayed. It may have been a temporary glitch.
