### ISSUE TITLE
Submit not allowed on page

### ISSUE THREAD

**Issue by DeadFishw** [Equim-chan/mjai-reviewer#110]
I cannot submit my request for reviewing my game or playing with me in tenhou for some reason. I searched for the answer but no one seems to have this problem.

**Comment by Equim-chan** [comment]
But you didn't even elaborate what you encountered like what kind of error message did you see.

**Comment by DeadFishw** [comment]
It seems like the problem is with cloudflare verify which did not appear on my screen.
