### ISSUE TITLE
Make the catalog of result page float

### ISSUE THREAD

**Issue by chucklu** [Equim-chan/mjai-reviewer#113]
Please  check this game https://mjai.ekyu.moe/report/f6ed57919cdb764e.html
When I scroll the web page, the catalog disappeared

an example
When I am viewing East-3, and now I want to switch to South-3, I have to scroll to the top to find the catalog

Where is the source code of web site mjai.ekyu.moe? maybe I can help with this feature, make the catalog float.

**Comment by Equim-chan** [comment]
The source code of the result page is at https://github.com/Equim-chan/mjai-reviewer/blob/master/templates/report.tera

**Comment by chucklu** [comment]
@Equim-chan  I just filed a pull request https://github.com/Equim-chan/mjai-reviewer/pull/114, which can make the catalog float.

**Comment by chucklu** [comment]
@Equim-chan  I have made another pull request https://github.com/Equim-chan/mjai-reviewer/pull/115, now the new css only work on PC web page. I have checked on mobile mode on web browser, the css should not work for mobile devices now.  And for the mobile devices, it's not possible to make a floated catalog, as there is no space to do this.
