### ISSUE TITLE
show the score of four players of each round in game summary part

### ISSUE THREAD

**Issue by chucklu** [Equim-chan/mjai-reviewer#117]
https://mjai.ekyu.moe/report/afdb2017df9edba7.html
{"dan":["雀士★3","雀士★1","雀傑★1","雀士★2"],"lobby":0,"log":[[[0,0,0],[25000,25000,25000,25000],[46],[],[47,43,29,43,36,32,14,21,12,44,14,17,39],[35,37,36,34,24,29,22,19,28,24,12,"c232224",15,16,46,42,22,41,45],[44,39,21,29,43,43,29,60,47,32,28,24,17,14,60,60,60,60,60],[22,21,32,16,23,27,28,45,45,42,21,33,33],[11,47,19,27,43,13,31,45,23,39,17,13,41,41,36,46,51],[60,21,60,42,60,27,33,47,13,60,23,60,60,60,60,60,45],[14,32,43,28,34,13,16,28,18,38,23,35,39],[47,18,35,38,38,44,24,42,31,37,"28p2828",18,36,27,13,39,41,19],[43,47,23,39,32,60,60,60,60,60,34,16,60,60,14,60,60,60],[42,44,47,15,21,29,24,31,26,46,25,11,11],[37,14,12,33,17,25,16,22,15,33,23,25,26,53,32,37,26,34],[60,42,44,46,29,21,25,60,47,31,60,60,60,33,60,33,24,14],["流局",[1000,1000,1000,-3000]]]],"name":["Aさん","Bさん","Cさん","Dさん"],"rate":[339.0,413.0,341.0,583.0],"ratingc":"PF4","rule":{"aka":0,"aka51":1,"aka52":1,"aka53":1,"disp":"銀の間南喰赤"},"sx":["C","C","C","C"]}

we have score status at the start of game [0,0,0],[25000,25000,25000,25000]
we also have the score status at the end of game ["流局",[1000,1000,1000,-3000]], we can calculate the score of four players

**Comment by Equim-chan** [comment]
Not sure what you mean but if I'm guessing it right, I think that'll make the title unnecessarily long.

Also, the scores are already displayed in a section.

![](https://github.com/Equim-chan/mjai-reviewer/assets/17795845/18ebc097-b471-4f7a-ba6d-5fa2f12a8457)

**Comment by chucklu** [comment]
@Equim-chan  just notice this, but is it possible to show the score summary at the end of game?
Or maybe we just show the end score of each game instead of the score at the start of game.

The first round all players are 25000 score, no need to show this, show result score of each round would be better.
The current design did not show the end score of last round game

**Comment by chucklu** [comment]
maybe add the result score of four players at the end of each round would be better, still keep showing the score at the start of game

**Comment by Equim-chan** [comment]
I think you could easily check that in the replay viewer or just scroll to the start of the next round if there's any. I have to admit the current report page is already somewhat messy so I don't want to add more unnecessary and redundant information to it.

**Comment by chucklu** [comment]
As I have mentioned, the score summary of last round of game is missed
