### ISSUE TITLE
Show the current location of player

### ISSUE THREAD

**Issue by chucklu** [Equim-chan/mjai-reviewer#121]
show 东南西北 of the current player, have no idea play the 北 is better, as I can't tell my current location
![image](https://github.com/Equim-chan/mjai-reviewer/assets/3004057/220f7ebe-726e-449b-ba2b-de2a82d32a0c)

**Comment by Equim-chan** [comment]
Why not just use the Replay Viewer tab? The tab is there for that purpose. You can also open the game log in your game in a separate window anyway.
