### ISSUE TITLE
Format of output of convlog?

### ISSUE THREAD

**Issue by HuCDver** [Equim-chan/mjai-reviewer#122]
I want to use convlog to transform mjlog json file (download from https://tenhou.net/5/mjlog2json.cgi?{log_id}) to mjai json. 

But it seems that the output of convlog in text is not a stardard json format: 
`[StartGame { names: ["", "", "", ""], kyoku_first: 0, aka_flag: true }, ... , EndKyoku, EndGame]`

While the mjai log I found in [mjai](http://gimite.net/mjai/log/) is something like:
`{"type":"start_game","names":["Manue013","Manue013","Manue013","tsumogiri"],"logs":["","","",null]}`

Am i using it correctly? 
Or what is the format of output of convlog? Is there any way i can transform it into json format?

**Comment by Equim-chan** [comment]
How did you _use_ convlog? convlog doesn't have a binary target so you shouldn't be able to run it.

**Comment by HuCDver** [comment]
Yes...
Here's my code:
`
    use convlog::*; 
    use std::fs::File;
    use std::io::prelude::*;

    ...

    let log = convlog::tenhou::Log::from_json_str(&mj_log).unwrap();
    let mjai_result = convlog::tenhou_to_mjai(&log).unwrap();

    let mut mjai_file = File::create(format!("{log_id}_mjai.json")).unwrap();
    mjai_file.write_fmt(format_args!("{:?}",mj_result)).expect("msg");
`

**Comment by HuCDver** [comment]
> Yes... Here's my code:
> 
> ```
>     let log = convlog::tenhou::Log::from_json_str(&mj_log).unwrap();
>     let mjai_result = convlog::tenhou_to_mjai(&log).unwrap();
> 
>     let mut mjai_file = File::create(format!("{log_id}_mjai.json")).unwrap();
>     mjai_file.write_fmt(format_args!("{:?}",mjai_result)).expect("msg");
> ```

Sorry. Just notice the output format is `Vec<Event>`.
