### ISSUE TITLE
Mortal needs permanent accounts on tenhou

### ISSUE THREAD

**Issue by Zeks** [Equim-chan/mjai-reviewer#128]
It's been bugging me for a while and I don't think I can ignore it any longer:

Even before I started playign with mortals I've been rolling a lot of new accounts and it felt like tenhou is doing *something* to spice up the hands of new accounts. They statisically were more likely to be strong and finish in bizarre ways. After I started playing with mortals AND nagas, it became pretty obvious that naga's hands are normal while mortal way too often recieves the typical "newbie" hand rng.

The problem got way worse with the introduction of 4.0 where mortal seems to have learned to take advantage of that and disproportinately go damaten. It really needs to get off its "I am a newbie" high and actually get registered so that the game doesn't treat it with kid's gloves.

I know people call me crazy, but it really feels like tenhou is doing something weird with their new accounts. It's nothing as overt as other servers where you just can't lose in your first games, but all my experience tells me *something* is fishy with that. It's just disproportionately too often that rng is rigged towards these

**Comment by Equim-chan** [comment]
Are you sure about that?🤔 I've never experienced such issue, nor have I ever thought about it, and I don't see the statistical evidence behind it. Even if it's true, how old do you think Tenhou would consider an account "old"? And what makes it "old" in the first place? Age or play counts? Does play counts on private lobby count or not? There are so many follow-up questions that I don't think it's worth delving deeper into them, but rather accept the assumption that the games are fair.

**Comment by Zeks** [comment]
_> Are you sure about that?_

Obviously not, it's just something that's been bugging me really really strongly. I've even played a seris of games vs naga, mortal and 8d tenhou and the only problem in those were actually mortals with their stupid bloody ridiculous early closed honitsus and the likes. Naga (almost) never demonstrates the same abundance of expensive closed hands early.

**Comment by Equim-chan** [comment]
Well, I don't think I could help with that...
