### ISSUE TITLE
Json output? Or some API?

### ISSUE THREAD

**Issue by killerducky** [Equim-chan/mjai-reviewer#129]
Is there a way to get the webpage https://mjai.ekyu.moe/ have an option to output JSON instead of html? Or is there an API to do the same? Currently I have a script that scrapes the HTML to pull some stats out but I'd rather not do it that way.

**Comment by Equim-chan** [comment]
JSON output is already available in the CLI, but it is highly internal and unstable, and breaking changes may be made at any time, so I didn't make it an option on the website. I also wonder if JSON output is actually helpful.
