### ISSUE TITLE
一个Review报告的bug

### ISSUE THREAD

**Issue by Fillianore** [Equim-chan/mjai-reviewer#130]
出自以下报告东一局：https://mjai.ekyu.moe/report/50e980b31c7a4f76.html
![image](https://github.com/Equim-chan/mjai-reviewer/assets/37468338/d49b3829-9c00-433c-8cbc-1c1dae08d1e0)
这里对同一个行动review了两次

**Comment by Equim-chan** [comment]
这实际上是两个动作，第一个动作是喊出立直（点立直按钮），第二个动作是选择立直宣言牌。

**Comment by Fillianore** [comment]
get 我后来也思考到了这个问题 非常感谢
