### ISSUE TITLE
想知道详情里面 这两个公式代表什么意思 

### ISSUE THREAD

**Issue by hakusai22** [Equim-chan/mjai-reviewer#142]
<img width="931" alt="image" src="https://github.com/Equim-chan/mjai-reviewer/assets/58761705/3029c72a-eb19-4e0e-962d-a5f152732d84">

**Comment by Equim-chan** [comment]
[FAQ](https://github.com/Equim-chan/mjai-reviewer/blob/master/faq.md#mortal-what-do-the-notations-mean) 里有写。
