### ISSUE TITLE
复盘过程中出现牌面缺失

### ISSUE THREAD

**Issue by luoxingtianming** [Equim-chan/mjai-reviewer#146]
最近使用复盘功能过程中出现部分牌的牌面变成空白，影响到了正常使用
![F7C15F05D4EB83A60772719D603E2219](https://github.com/user-attachments/assets/de525aa8-cfec-40f1-abf3-d6f1ee5845c0)

**Comment by luoxingtianming** [comment]
刷新测试之后实际上发现还是有类似问题，使用的还是之前的谱
![e9542717-786c-4a82-9754-3220a3ae80ed](https://github.com/user-attachments/assets/d7729531-0649-4d11-b6f0-3674da88a732)

**Comment by luoxingtianming** [comment]
另外，使用原先classic版本的界面没有类似问题，供您参考，谢谢

**Comment by Equim-chan** [comment]
试试强制刷新(Ctrl + F5)。

**Comment by luoxingtianming** [comment]
目前尝试后没有再出现类似问题了，谢谢！
