### ISSUE TITLE
"failed to download game log" for all recent logs

### ISSUE THREAD

**Issue by seraxis** [Equim-chan/mjai-reviewer#152]
All recent game logs I've attempted to review have met the same error, some examples

https://game.mahjongsoul.com/?paipu=jmkknr-0uq5x768-xy1e-66df-fifg-qlqmkkooupzu_a413602829_2
https://game.mahjongsoul.com/?paipu=jmkknq-ytqw35z7-4708-69b8-ic9c-glpkjuxqqovp_a413602829_2

**Comment by AprilGrimoire** [comment]
Same for me. Seems majsoul updated their log format.

**Comment by Equim-chan** [comment]
Fixed.
