### ISSUE TITLE
负分牌谱无法进行review

### ISSUE THREAD

**Issue by HALF111** [Equim-chan/mjai-reviewer#154]
打比赛场类似于mleague为无击飞规则，但是负分的牌谱在mortal无法进行review，请问这个应该如何设置/处理呢？

**Comment by Equim-chan** [comment]
Mortal 本身不支持负分牌谱。如果硬要 review 的话只能把点数修改成正的。

**Comment by HALF111** [comment]
哦哦哦明白了，不过想再请教下如何把点数修改成正的呢

**Comment by Equim-chan** [comment]
这个比较麻烦，没有什么方便的办法。

**Comment by HALF111** [comment]
明白了，非常感谢！那另外问问像naga或者有无其他AI是能支持负分的谱呢🥹，因为有些像mleague的谱可能也想拿去跑
