### ISSUE TITLE
Error when trying to analyse Jantama logs

### ISSUE THREAD

**Issue by SuperExpressIwaki** [Equim-chan/mjai-reviewer#23]
Windows 10でリリースv0.6.0が雀魂牌譜に限り動作不能になりました。URLを入力してしばらく置いていくとHTTP 500というエラーコードが出てしまう。できれば修復作業お願いします。
Error HTTP 500 appears for Jantama logs using release v0.6.0 on Windows 10

**Comment by Equim-chan** [comment]
I cannot reproduce this. Do you have any http proxy enabled?

**Comment by SuperExpressIwaki** [comment]
プロキシがオフで、雀魂サーバーとの接続も確保した（Chromeでゲームにログインできる）が、それでもダウンロードできません。天鳳の場合は問題ないので雀魂側の問題だと思う。
Still not able to download logs while system proxy has been set to 'OFF' and successfully log in to the game using Chrome browser. No such problem for Tenhou logs so may be something wrong at Jantama server.

> PS Y:\akochan> ./akochan-reviewer.exe "https://game.mahjongsoul.com/?paipu=210731-64f58ecd-5e80-4280-8105-65e4a343aaa3_a421417513"

Enterを押した後約20秒経過して次のメッセージが表示される

>Error: failed to download mahjong soul log 210731-64f58ecd-5e80-4280-8105-65e4a343aaa3_a421417513
>
>Caused by:
>    get mahjong soul log: 500 Connection Failed

**Comment by Equim-chan** [comment]
Are you able to access https://tensoul.herokuapp.com/ ?

**Comment by SuperExpressIwaki** [comment]
プロキシがオフの状態では接続ができません。中継サーバーを使って当該ドメインとの接続を確保すればあこちゃんが通常通り動くことになるので、そこが問題だと思います。ありがとうございました。
追記：インターネット接続に問題が発生する場合はエラーメッセージにターゲットドメインを表記するほうがいいと思います。トラブルシューティングの手がかりになるかもしれません。
Cannot connect to that domain with proxy off. Program now works normally when an intermediate server has been employed for connection between local and the server. Thanks a lot for helping.
ps: it may be an advantage to show target domain or server that causes error in message for effective troubleshooting.
