### ISSUE TITLE
Missing Shouminkan turn

### ISSUE THREAD

**Issue by Hohol** [Equim-chan/mjai-reviewer#28]
`./akochan-reviewer.exe --lang en -e -n 0.005 "https://tenhou.net/0/?log=2021082908gm-0089-0000-369d5ba3&tw=0"`
In South 4:
![image](https://user-images.githubusercontent.com/2988117/131234299-3d0a64e4-de54-4528-bd3b-cf3e9d0fe020.png)
The review jumps from Turn 2 to Turn 5, the turn when I made pon into kan is missing.

**Comment by yueclipse** [comment]
Same with build from source. Missing Shouminkan on Hatsu. Is this reviewer's problem or algorithm?

WARNING: unable to find player's action in akochan's return, expected to find: [Kakan { actor: 3, pai: Hatsu, consumed: [Hatsu, Hatsu, Hatsu] }], list: [[Dahai { actor: 3, pai: Hatsu, tsumogiri: true }], [Dahai { actor: 3, pai: Man9, tsumogiri: false }], [Dahai { actor: 3, pai: Sou6, tsumogiri: false }], [Dahai { actor: 3, pai: AkaPin5, tsumogiri: false }], [Dahai { actor: 3, pai: Man7, tsumogiri: false }], [Dahai { actor: 3, pai: Man6, tsumogiri: false }], [Dahai { actor: 3, pai: Pin9, tsumogiri: false }], [Dahai { actor: 3, pai: Haku, tsumogiri: false }]]

WARNING: unable to find player's action in akochan's return, expected to find: [Kakan { actor: 3, pai: Hatsu, consumed: [Hatsu, Hatsu, Hatsu] }], list: [[Dahai { actor: 3, pai: Pin1, tsumogiri: false }], [Dahai { actor: 3, pai: Pin7, tsumogiri: false }], [Dahai { actor: 3, pai: Hatsu, tsumogiri: true }], [Dahai { actor: 3, pai: Pin5, tsumogiri: false }], [Dahai { actor: 3, pai: Pin3, tsumogiri: false }], [Dahai { actor: 3, pai: Sou4, tsumogiri: false }], [Dahai { actor: 3, pai: Sou3, tsumogiri: false }], [Dahai { actor: 3, pai: AkaMan5, tsumogiri: false }], [Dahai { actor: 3, pai: Man6, tsumogiri: false }]]

**Comment by Equim-chan** [comment]
It's an akochan issue.
