### ISSUE TITLE
Add support of paipus files downloaded from MajsoulPaipuAnalyzer.

### ISSUE THREAD

**Issue by 185264646** [Equim-chan/mjai-reviewer#33]
MajsoulPaipuAnalyzer is a software developed by @zyr17 . The paipus file that the software uses is different from tenhou. Using that file to get paipus file is much easier than installing TamperMankey plugin and download then manually.

**Comment by syooool** [comment]
> I made a test version to generate tenhou logs for all downloaded paipus. I tested with a four-south ranked game played on Oct. 15th, 2021, and it seems to work well.
> 
> I also found that the script can't convert paipus recorded before June, 2021 (e.g. 190222-7fdcb61b-3157-4522-862d-e0ac2486dbd1). The ProtoBuf structure of old logs is `GameRestore`, and save data in `GameRestore.actions`, while newer logs use `GameAction` and save in `GameAction.results`. I thought analyzing logs before three months is less useful, so I didn't fix it.
> 
> You can try it by downloading the test version from GitHub Actions. Now the PaipuCrawler is still only in Chinese. https://github.com/zyr17/MajsoulPaipuAnalyzer/actions/runs/1383941629

how to "generate tenhou logs for all downloaded paipus" in your project?

**Comment by zyr17** [comment]
> 
> how to "generate tenhou logs for all downloaded paipus" in your project?

For Chinese users, please refer to the readme of  `MajsoulPaipuAnalyzer`. Here are the quick steps of version 0.5.0 for non-Chinese users.
- Select the correct server by clicking 网页 in the menu, and select server. 进入中文服 = Chinese, 进入日服 = Japanese, 进入国际服 = International (English). 
- Login into majsoul. If some errors occur in logging, you can click 网页 - 登录专用窗口 to try login in an extra window, then click 网页 - 刷新 to see if can login. 
- Click 牌谱 - 自动获取牌谱数据 and 确定 for the popup. Wait for some time (usually 1min for 1000 records) until a popup with `已自动收集牌谱基本数据！牌谱个数：xxx`. 
- Click 牌谱 - 下载&转换牌谱 and 确定 for popups. The progress will show on the top left of the other SimpleMahjong window. Every four-south paipu will process for about one second. 
- Click 牌谱 - 转换天凤牌谱 and 确定 for the popup. All majsoul paipus will be tried to convert. Wait some time until a popup with the title `转换完成` is shown. The save place of tenhou type logs is shown in the popup.

**Comment by Equim-chan** [comment]
Closed due to inactivity.
