### ISSUE TITLE
East game of Mahjong Soul Logs doesn't acknowledged as East game.

### ISSUE THREAD

**Issue by bupjae** [Equim-chan/mjai-reviewer#60]
For example, East game log generated by [log extractor](https://gist.githubusercontent.com/Equim-chan/875a232a2c1d31181df8b3a8704c3112/raw/a0533ae7a0ab0158ca9ad9771663e94b82b61572/downloadlogs.js) contains word "East" on `rule.disp`.

However, in akochan-reviewer,  only word '東' is checked whether the game is Tonpuu (East) game; if not, the log is examined as Hanchan (South) game.

For workaround, I manually modify log file to add word '東' in `rule.disp`. But, it would be better if akochan-review could recognize word 'East' as Tonpuu (East) game.

**Comment by Equim-chan** [comment]
This is a known issue and will be fixed in the next major version.
