### ISSUE TITLE
Mortal engine can't analyze tenhou tournament lobby game

### ISSUE THREAD

**Issue by Nihisil** [Equim-chan/mjai-reviewer#68]
Example of the log: https://tenhou.net/3/?log=2022062622gm-0009-12717-4ba5fb37&tw=1

Error when I'm trying to analyze the log on https://mjai.ekyu.moe/

> 2022062622gm-0009-12717-4ba5fb37 does not look like a valid 4-player tenhou log ID, or some error occurred when parsing it

**Comment by Equim-chan** [comment]
This is a bug of Tenhou itself. mjai-reviewer reads tenhou.net/6 format log as input, but the log your provided cannot be loaded by tenhou.net/6 (https://tenhou.net/6/?log=2022062622gm-0009-12717-4ba5fb37&tw=1).

**Comment by hyskylord** [comment]
Some Houou games cannot be parsed too, but it seems they return different values.
tournament games will just return empty json, but Houou games like http://tenhou.net/6/?log=2021092601gm-00a9-0000-179c6ce0 returns 404 NOT FOUND.
