### ISSUE TITLE
Mortal suggested Riichi but didn't show which tile to Riichi with.

### ISSUE THREAD

**Issue by celie1** [Equim-chan/mjai-reviewer#69]
https://mjai.ekyu.moe/report/51c42f00f73f66e1.html

![image](https://user-images.githubusercontent.com/71301903/176107480-273d8ad5-b3cd-49fc-87de-5ffcf0af19c0.png)

There are 4 tiles to Riichi ( 2s 0s 7m 8m )

**Comment by Equim-chan** [comment]
This is by design. For Mortal, deciding whether to riichi and deciding what to discard right after riichi are two separate scenes.
