### ISSUE TITLE
Mortal的选择和玩家一致，但玩家的选择被标红

### ISSUE THREAD

**Issue by cloudfish** [Equim-chan/mjai-reviewer#74]
标题很难用一句话描述清楚问题，详见截图。
![2022-07-14 16-18-34 创建的截图](https://user-images.githubusercontent.com/13962946/178936317-ebcae219-01ee-4352-b2fe-55a0ffc37da7.png)
牌谱（玩家2）：https://game.maj-soul.net/1/?paipu=220714-daecdd73-bbe9-4929-a350-022a926fc598_a61478031
分析结果（东2局第15巡）：https://mjai.ekyu.moe/report/9d4ad10d9a492a35.html

**Comment by Nihisil** [comment]
Same error on "East 1": https://mjai.ekyu.moe/report/1cdbf07647787db0.html

![image](https://user-images.githubusercontent.com/475367/181026260-21e60c0a-dc08-43b9-807d-23c687d0c9b6.png)
