### ISSUE TITLE
How did you obtain the data from Jantama?

### ISSUE THREAD

**Issue by kbkn3** [Equim-chan/mjai-reviewer#78]
Could you please tell me how you obtained the data for one game in the mjai-reviewer service before it was closed?
I want to create one fun service by getting data from the server per game, not in large quantities.
I'm sorry if it's hard to understand because my English is not very good.

**Comment by celie1** [comment]
> Could you please tell me how you obtained the data for one game in the mjai-reviewer service before it was closed? I want to create one fun service by getting data from the server per game, not in large quantities. I'm sorry if it's hard to understand because my English is not very good.

Maybe you can try this?
https://github.com/MahjongRepository/phoenix-logs

**Comment by Equim-chan** [comment]
Check out [Equim-chan/tensoul](https://github.com/Equim-chan/tensoul).

**Comment by kbkn3** [comment]
Thank you. I will refer to it.
