### ISSUE TITLE
反馈：机器人验证一直失败

### ISSUE THREAD

**Issue by Clouxin** [Equim-chan/mjai-reviewer#88]
![IMG_20221107_003640](https://user-images.githubusercontent.com/32696551/200185745-8c5be900-d36e-4735-ad92-1bbc7066fe40.jpg)
这个clouflare验证最近无限failure，裸连的话这个验证一直转圈圈，然后切换各个节点都不行，但是之前能用。隔一两天尝试大概试了三四次还是这样，这样就没法使用了，反馈一下

**Comment by Equim-chan** [comment]
换个浏览器看看

**Comment by Clouxin** [comment]
> 换个浏览器看看

下了chrome确实好了谢谢，原来用的via，不知道为什么就不能用了。只是要多装个浏览器……另外也发现牌谱播放不会总是偏移出界面了，可能真是浏览器的问题

**Comment by Clouxin** [comment]
顺便一提，有希望出个类似akochan哭笑脸标签的不同切法的差异度分级吗，帮助使用者一眼通过标签快速区分大体程度，比如第一打的优先度超过某个界限值以及与第二打等其余打的差距值之类。

**Comment by Clouxin** [comment]
@Equim-chan

**Comment by Equim-chan** [comment]
最近暂时没什么精力
