### ISSUE TITLE
[Bug]关于暗杠加杠之后四杠散了触发mortal崩溃

### ISSUE THREAD

**Issue by Pragmatism0220** [Equim-chan/mjai-reviewer#92]
[契机]自己本地的mortal报了错，所以想去在线版mortal验证（https://mjai.ekyu.moe/）
[复现]在mortal网页上提交牌谱（https://game.maj-soul.net/1/?paipu=221016-df7f1dcb-4ab9-487d-86a4-3f773fbaff62_a458251274）即可。
[表现]如下图所示
![image](https://user-images.githubusercontent.com/55100969/205426924-ff99d05e-879a-4422-9941-4a1815eb53b8.png)

**Comment by Equim-chan** [comment]
是 reviewer 的问题，已经修复了。
