### ISSUE TITLE
Turns missing after claiming a discard

### ISSUE THREAD

**Issue by nagisa-eevee** [Equim-chan/mjai-reviewer#99]
In the first two turns, I claim discards and they are omitted. The results starts from the third turns.
The detailed situation is displayed at below:
这局我前两巡鸣牌，结果牌谱检讨里只包括从第三巡第一次摸牌开始的分析；前两次鸣牌的判断没有展示。具体情形见下图所示：
 
![屏幕截图_20230211_143217](https://user-images.githubusercontent.com/46982956/218244367-fe73e9d4-366b-4e60-825b-172c0c2dbfdc.png)
![屏幕截图_20230211_143448](https://user-images.githubusercontent.com/46982956/218244435-779431c3-8fa3-4012-b7ff-f89d6fe98e8a.png)

**Comment by Equim-chan** [comment]
用 1.x.x 版本再试一下，v0 已经不再维护。

**Comment by nagisa-eevee** [comment]
> 用 1.x.x 版本再试一下，v0 已经不再维护。

谢谢，新版本没有这个问题
